name: CS4243

channels:
  - tensorflow
  - conda-forge

dependencies:
  - python=3.9
  - numpy
  - jupyter
  - scipy
  - pandas
  - matplotlib
  - scikit-learn
  - tensorflow=2.9
  - opencv
  - pip

  - pip:
    - imutils
