name: CS4243

channels:
  - tensorflow
  - conda-forge

dependencies:
  - python=3.8
  - numpy=1.21.1
  - jupyter=1.0.0
  - scipy=1.7.1
  - pandas=1.3.1
  - matplotlib=3.4.2
  - scikit-learn=0.24.2
  - tensorflow=2.9
  - opencv
  - pytest

  - pip:
    - imutils